spring:
  application:
    name: coin-community-backend

  datasource:
    url: jdbc:mysql://localhost:3306/coin_community?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        use_sql_comments: false
    defer-datasource-initialization: true

  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
    time-zone: Asia/Seoul

jwt:
  secret: Y29pbi1jb21tdW5pdHktYmFja2VuZC1qd3Qtc2VjcmV0LWtleS1mb3ItYXV0aGVudGljYXRpb24tYW5kLWF1dGhvcml6YXRpb24=
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

# CORS 설정
cors:
  allowed-origins: "http://localhost:3000,http://localhost:3001,http://127.0.0.1:3000"
  allowed-origins-list:
    - http://localhost:3000
    - http://localhost:3001
    - http://127.0.0.1:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
    - X-Requested-With
    - Accept
    - Origin
    - Access-Control-Request-Method
    - Access-Control-Request-Headers
  expose-headers:
    - Authorization
  allow-credentials: true
  max-age: 3600

external:
  # 기본 코인 가격 API (단순화)
  coingecko:
    base-url: https://api.coingecko.com
    version: api/v3

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
